export const CODE_VARIANTS: CodeGenVariant[] = [
  { lang: 'curl', variant: 'curl', label: 'cURL — cURL' },
  { lang: 'javascript', variant: 'fetch', label: 'JavaScript — Fetch' },
  { lang: 'javascript', variant: 'jquery', label: 'JavaScript — jQuery' },
  { lang: 'javascript', variant: 'xhr', label: 'JavaScript — XHR' },
  { lang: 'nodejs', variant: 'axios', label: 'NodeJs — Axios' },
  { lang: 'nodejs', variant: 'native', label: 'NodeJs — Native' },
  { lang: 'nodejs', variant: 'request', label: 'NodeJs — Request' },
  { lang: 'nodejs', variant: 'unirest', label: 'NodeJs — Unirest' },
  { lang: 'python', variant: 'requests', label: 'Python — Requests' },
  { lang: 'java', variant: 'okhttp', label: 'Java — OkHttp' },
  { lang: 'java', variant: 'unirest', label: 'Java — Unirest' },
  { lang: 'csharp', variant: 'httpclient', label: 'C# — HttpClient' },
  { lang: 'csharp', variant: 'restsharp', label: 'C# — RestSharp' },
  { lang: 'go', variant: 'native', label: 'Go — Native' },
];
